[book]
authors = ["cympfh"]
language = "en"
multilingual = false
src = "src"
title = "dosoku"

[preprocessor.mathjax]
command = "ruby preprocessor/mathjax.rb"
renderer = ["html"]

[output.html]
mathjax-support = true
