[project]
name = "paper-new"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "rich>=14.0.0",
    "watchgod>=0.8.2",
]
