#!/bin/bash

upload() {
    imgur up --title "$1" -A neta "$1"
}

TMPFILE=/tmp/description
cat <<EOM >$TMPFILE

# $1
EOM
vim $TMPFILE
description="$(sed 's/^#.*$//g' $TMPFILE | tr '[A-Z]\n' '[a-z] ' | sed 's/  */ /g; s/ *$//g; s/^ *//g')"
url=$(upload "$1")

echo "{\"url\": \"${url}\", \"description\": \"${description}\"}" |
tee -a db.jsonl
