#!/bin/bash

upload() {
    echo imgur up -A neta "$1" >&2
    imgur up -A neta "$1"
}

url=$(upload "$1")

TMPFILE=/tmp/description
cat <<EOM >$TMPFILE

# Original: $1
# Uploaded: $url
EOM
vim $TMPFILE
description="$(sed 's/^#.*$//g' $TMPFILE | tr '[A-Z]\n' '[a-z] ' | sed 's/  */ /g; s/ *$//g; s/^ *//g')"

# echo "{\"url\": \"${url}\", \"description\": \"${description}\"}" |
qj -e .url="$url" .description="$description" | tee -a db.jsonl
